Repository blocto/blocto-android-sdk, pull requests merged in 2023-07, with the labels that each got.

#40 [EVM] Update Demo sign message format
  app/src/main/java/com/portto/valuedapp/evm/EvmSignMessageFragment.kt
Labels: bug

#41 [EVM] Add custom RPC url field
  app/src/main/java/com/portto/valuedapp/evm/EvmSendTransactionFragment.kt
  app/src/main/java/com/portto/valuedapp/evm/EvmSignMessageFragment.kt
  app/src/main/java/com/portto/valuedapp/evm/EvmValueDappActivity.kt
  app/src/main/java/com/portto/valuedapp/evm/EvmViewModel.kt
  app/src/main/res/layout/activity_evm_value_dapp.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#42 [EVM] Clear RPC url when changing env
  app/src/main/java/com/portto/valuedapp/evm/EvmValueDappActivity.kt
  app/src/main/res/layout/activity_evm_value_dapp.xml
Labels: refactoring
